language: python
python:
  - "3.5"
  - "3.6"
install:
  - "pip install -r test_requirements.txt"
script:
  - "flake8 --config flake8.cfg ."
  - "pep257 --ignore=D100,D103,D104,D200,D202,D203,D205,D400,D401,D402"
