# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
black: false
check_commit_message: true
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docs_test: true
plugin_app_label: python
plugin_camel: PulpPython
plugin_camel_short: Python
plugin_caps: PULP_PYTHON
plugin_caps_short: PYTHON
plugin_dash: pulp-python
plugin_dash_short: python
plugin_name: pulp_python
plugin_snake: pulp_python
pydocstyle: true
pypi_username: pulp
test_bindings: false
test_performance: false
travis_notifications: None

